### ISSUE TITLE
网络错误，无法上传图片

### ISSUE THREAD

**Issue by Bloak** [aimerneige/MiraiChess#18]
![Screen Shot 2022-12-02 at 1 19 25 PM](https://user-images.githubusercontent.com/55962111/205360941-2e7b5a57-19ca-421a-bea8-61d2c5e5ef54.png)
![Screen Shot 2022-12-02 at 1 19 38 PM](https://user-images.githubusercontent.com/55962111/205360952-84c0c4f3-f806-4126-a421-42524969d074.png)

**Comment by aimerneige** [comment]
服务器网络问题，可能是被腾讯风控了，重启即可。
