### ISSUE TITLE
建议增加群员ELO排行功能

### ISSUE THREAD

**Issue by Silver-Fang** [aimerneige/MiraiChess#7]
如题，给第一次下棋的群员一个初始ELO，然后每局后结算ELO变化，并且提供一个命令查看当前群员ELO排行

**Comment by Silver-Fang** [comment]
最好还能给群主特殊权限，可以设置初始ELO值、ELO算法参数等

**Comment by aimerneige** [comment]
感谢提议，已纳入开发计划中。

**Comment by aimerneige** [comment]
<https://en.wikipedia.org/wiki/Elo_rating_system>

**Comment by aimerneige** [comment]
- [ ] 弃赛检测
- [ ] 对局建立后一方离线

**Comment by Silver-Fang** [comment]
> * [ ]  弃赛检测
> * [ ]  对局建立后一方离线

确实应该有个弃赛检测，比如率先开局的一方可以规定每步限时，超时自动判负；如果没规定就给一个默认限时，可以长一点。
